apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
        env: prod
    spec:
      containers:
        - name: odoo
          image: odoo:13.0
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: postgres
            - name: PORT
              value: "5432"
            - name: DB_NAME
              value: odoo
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: odoo-secret
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-secret
                  key: password
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-pvc
