apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  type: ClusterIP
  selector:
    app: odoo
  ports:
    - port: 8069
      targetPort: 8069
