apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-web
  namespace: icgroup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-web
  template:
    metadata:
      labels:
        app: site-web
    spec:
      containers:
      - name: site-web
        image: image: abdoul223/ic-webapp:1.0
        ports:
        - containerPort: 5000
        env:
        - name: ODOO_URL
          value: http://odoo:8069
        - name: PGADMIN_URL
          value: http://pgadmin:80
