containers:
  - name: site-web
    image: abdoul223/ic-webapp:1.0
    ports:
      - containerPort: 5000
    env:
      - name: ODOO_URL
        value: http://odoo:8069
      - name: PGADMIN_URL
        value: http://pgadmin:80
    command: ["python3"]
    args: ["app.py", "--host=0.0.0.0", "--port=5000"]
