apiVersion: v1
kind: Service
metadata:
  name: site-web
  namespace: icgroup
spec:
  type: NodePort
  selector:
    app: site-web
  ports:
    - port: 80
      targetPort: 8080     # ← DOIT correspondre à containerPort
      nodePort: 30081      # ← Choisis un port entre 30000-32767
