apiVersion: v1
kind: Service
metadata:
  name: site-web
  namespace: icgroup
spec:
  type: NodePort
  selector:
    app: site-web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30081

