apiVersion: v1
kind: Service
metadata:
  name: site-web
  namespace: icgroup
spec:
  type: NodePort
  selector:
    app: site-web
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30081

